name: "Terraform with Checkov - Destroy"
 
on:
 workflow_dispatch:
 
env:
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
 terraform:
   name: "Terraform with Checkov - Security Scan and Deploy"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
 
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
     - name: Setup SSH key
       run: |
         echo "${{ secrets.EC2_KEY_PAIR }}" > key.pem
         chmod 400 key.pem
     
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0
     
     - name: Terraform init
       run: terraform init 

     - name: Download tfvars
       uses: actions/download-artifact@v4
       with:
         name: tf-output
     
     - name: Terraform Destroy
       run: terraform destroy -var-file=tf-output.auto.tfvars -auto-approve
